services:
  ansible:
    build: .
    container_name: opi5-eye  # Nome personalizado do container
    volumes:
      - .:/app
    environment:
      - GIT_REPOS=${GIT_REPOS}
      - GIT_BRANCHES=${GIT_BRANCHES}
      - CONTAINER_PATHS=${CONTAINER_PATHS}
    tty: true
    networks:
      - pinet

networks:
  pinet:
    external: true
