services:
  ansible:
    build: .
    container_name: ansible
    volumes:
      - .:/app
    environment:
      - GIT_REPO_URL=${GIT_REPO_URL}
      - GIT_BRANCH=${GIT_BRANCH}
      - CONTAINER_PATH=${CONTAINER_PATH}
    tty: true
    networks:
      - pinet
networks:
  pinet:
    external: true